<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>mockingbird-transports-camel</artifactId>
        <groupId>org.qubership.mockingbird</groupId>
        <version>5.0.30-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>mockingbird-transport-sql</artifactId>
    <name>mockingbird-transport-sql</name>
    <packaging>jar</packaging>

    <build>
        <finalName>mockingbird-transport-sql</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib/${project.build.finalName}</outputDirectory>
<!--                            <excludeTransitive>true</excludeTransitive>-->
                            <excludeGroupIds>
                                org.springframework,
                                org.springframework.boot,
                                org.springframework.cloud,
                                org.springdoc,
                                org.hibernate.orm,
                                org.hibernate.validator,
                                org.qubership.atp.auth,
                                org.qubership.atp.common,
                                org.javers,
                                org.liquibase,
                                io.github.openfeign,
                                io.micrometer,
                                io.prometheus,
                                io.undertow,
                                io.swagger.core.v3,
                                org.webjars,
                                net.javacrumbs.shedlock,
                                net.bytebuddy,
                                org.bouncycastle</excludeGroupIds>
                            <!--if you have NoClassFoundException for this transport then include required dependency here-->
                            <includeScope>runtime</includeScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-dbcp2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-cassandraql</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.fasterxml.jackson.core</groupId>-->
<!--            <artifactId>jackson-databind</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.checkerframework</groupId>
                    <artifactId>checker-qual</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.codahale.metrics</groupId>-->
<!--            <artifactId>metrics-core</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>io.trino</groupId>
            <artifactId>trino-jdbc</artifactId>
            <version>440</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-jdbc</artifactId>
            <version>4.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
