openapi: 3.0.1
info:
  title: ITF Executor API
  description: ITF Executor API
  version: '1.1'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: context-controller
    description: Context Controller
paths:
  '/context/get':
    get:
      tags:
        - context-controller
      summary: get
      operationId: get
      parameters:
        - name: id
          in: query
          description: contextId
          required: true
          schema:
            type: string
        - name: projectUuid
          in: query
          description: projectUuid
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
